import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../../auth/presentation/providers/auth_provider.dart';
import '../../domain/models/trip_model.dart';
import '../providers/trip_provider.dart';

class CreateTripStep3Screen extends ConsumerStatefulWidget {
  const CreateTripStep3Screen({super.key});

  @override
  ConsumerState<CreateTripStep3Screen> createState() =>
      _CreateTripStep3ScreenState();
}

class _CreateTripStep3ScreenState extends ConsumerState<CreateTripStep3Screen> {
  final _overallBudgetController = TextEditingController();
  final _dailyLimitController = TextEditingController();
  String _selectedPace = 'balanced'; // Default

  @override
  void dispose() {
    _overallBudgetController.dispose();
    _dailyLimitController.dispose();
    super.dispose();
  }

  Future<void> _onCreateTrip() async {
    final user = ref.read(currentUserProvider);
    if (user == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('You must be logged in to create a trip')),
      );
      return;
    }

    final draft = ref.read(createTripDraftProvider);
    // Basic validation
    if (draft['name'] == null ||
        draft['start_date'] == null ||
        draft['end_date'] == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
            content: Text('Missing trip information. Please restart.')),
      );
      return;
    }

    // Parse budget
    final overallBudget = double.tryParse(_overallBudgetController.text);
    final dailyLimit = double.tryParse(_dailyLimitController.text);

    // Create Trip Object
    final newTrip = Trip(
      id: '', // Will be generated by DB
      name: draft['name'],
      startDate: draft['start_date'],
      endDate: draft['end_date'],
      defaultCurrency: draft['default_currency'] ?? 'USD',
      overallBudget: overallBudget,
      dailyLimit: dailyLimit,
      travelPace: _selectedPace,
      createdBy: user.id,
      status: 'planning',
      // coverImageUrl: Fetch for destination? Omitted for now.
    );

    // Save
    try {
      final tripController = ref.read(userTripsProvider.notifier);
      final tripRepo = ref.read(tripRepositoryProvider);

      // 1. Create Trip
      final createdTrip = await tripController.createTrip(newTrip);

      // 2. Upload Cover Image (if selected)
      final coverImagePath = draft['cover_image_path'];

      if (coverImagePath != null) {
        final imageUrl =
            await tripRepo.uploadTripCover(createdTrip.id, coverImagePath);

        // 3. Update Trip with Image URL
        final updatedTrip = createdTrip.copyWith(coverImageUrl: imageUrl);
        await tripController.updateTrip(updatedTrip);
      }

      // Clear draft
      ref.read(createTripDraftProvider.notifier).state = {};

      if (mounted) {
        context.go('/');
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Failed to create trip: $e')),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        backgroundColor: Theme.of(context).colorScheme.surface,
        appBar: AppBar(
          title: const Text('Create Trip'),
          centerTitle: true,
          leading: IconButton(
            icon: const Icon(Icons.arrow_back),
            onPressed: () => context.pop(),
          ),
        ),
        body: Column(
          children: [
            // Step Progress
            Padding(
              padding: const EdgeInsets.symmetric(vertical: 16.0),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  _buildStepIndicator(1, false, completed: true),
                  _buildStepLine(true),
                  _buildStepIndicator(2, false, completed: true),
                  _buildStepLine(true),
                  _buildStepIndicator(3, true),
                ],
              ),
            ),

            Expanded(
              child: SingleChildScrollView(
                padding: const EdgeInsets.all(24.0),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      'Preferences',
                      style:
                          Theme.of(context).textTheme.headlineMedium?.copyWith(
                                fontWeight: FontWeight.bold,
                              ),
                    ),
                    const SizedBox(height: 8),
                    Text(
                      'Set your budget and travel style preferences.',
                      style: Theme.of(context).textTheme.bodyLarge?.copyWith(
                            color: Colors.grey,
                          ),
                    ),
                    const SizedBox(height: 32),

                    // Budget Section
                    Text('Trip Budget',
                        style: Theme.of(context).textTheme.titleMedium),
                    const SizedBox(height: 12),
                    Row(
                      children: [
                        Expanded(
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Text('Overall',
                                  style: Theme.of(context)
                                      .textTheme
                                      .labelSmall
                                      ?.copyWith(color: Colors.grey)),
                              const SizedBox(height: 4),
                              TextField(
                                controller: _overallBudgetController,
                                keyboardType: TextInputType.number,
                                decoration: InputDecoration(
                                  prefixIcon: const Icon(
                                      Icons.account_balance_wallet,
                                      color: Colors.grey),
                                  hintText: '2000',
                                  filled: true,
                                  fillColor: Theme.of(context)
                                      .colorScheme
                                      .surfaceContainerHighest
                                      .withValues(alpha: 0.3),
                                  border: OutlineInputBorder(
                                      borderRadius: BorderRadius.circular(12),
                                      borderSide: BorderSide.none),
                                ),
                              ),
                            ],
                          ),
                        ),
                        const SizedBox(width: 12),
                        Expanded(
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Text('Daily Limit',
                                  style: Theme.of(context)
                                      .textTheme
                                      .labelSmall
                                      ?.copyWith(color: Colors.grey)),
                              const SizedBox(height: 4),
                              TextField(
                                controller: _dailyLimitController,
                                keyboardType: TextInputType.number,
                                decoration: InputDecoration(
                                  prefixIcon: const Icon(Icons.savings,
                                      color: Colors.grey),
                                  hintText: '150',
                                  filled: true,
                                  fillColor: Theme.of(context)
                                      .colorScheme
                                      .surfaceContainerHighest
                                      .withValues(alpha: 0.3),
                                  border: OutlineInputBorder(
                                      borderRadius: BorderRadius.circular(12),
                                      borderSide: BorderSide.none),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ],
                    ),

                    const SizedBox(height: 32),
                    const Divider(),
                    const SizedBox(height: 32),

                    // Pace Section
                    Text('Travel Pace',
                        style: Theme.of(context).textTheme.titleMedium),
                    const SizedBox(height: 12),
                    Row(
                      children: [
                        Expanded(
                            child: _buildPaceOption(
                                'relaxed', Icons.hot_tub, 'Relaxed')),
                        const SizedBox(width: 8),
                        Expanded(
                            child: _buildPaceOption(
                                'balanced', Icons.hiking, 'Balanced')),
                        const SizedBox(width: 8),
                        Expanded(
                            child: _buildPaceOption(
                                'packed', Icons.bolt, 'Packed')),
                      ],
                    ),

                    const SizedBox(height: 32),

                    // Categories Mock
                    Text('Categories Enabled',
                        style: Theme.of(context).textTheme.titleMedium),
                    const SizedBox(height: 12),
                    Wrap(
                      spacing: 8,
                      runSpacing: 8,
                      children: [
                        _buildCategoryChip(Icons.restaurant, 'Food', true),
                        _buildCategoryChip(
                            Icons.directions_bus, 'Transport', true),
                        _buildCategoryChip(Icons.hotel, 'Stay', true),
                        _buildCategoryChip(
                            Icons.local_activity, 'Activities', false),
                        _buildCategoryChip(
                            Icons.shopping_bag, 'Shopping', false),
                      ],
                    )
                  ],
                ),
              ),
            ),

            // Bottom Bar
            Container(
              padding: const EdgeInsets.all(16),
              decoration: BoxDecoration(
                color: Theme.of(context).scaffoldBackgroundColor,
                boxShadow: [
                  BoxShadow(
                    color: Colors.black.withValues(alpha: 0.05),
                    blurRadius: 10,
                    offset: const Offset(0, -5),
                  ),
                ],
              ),
              child: SizedBox(
                width: double.infinity,
                height: 56,
                child: FilledButton(
                  onPressed: _onCreateTrip,
                  style: FilledButton.styleFrom(
                    shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(16)),
                  ),
                  child: const Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      Icon(Icons.check),
                      SizedBox(width: 8),
                      Text('Create Trip'),
                    ],
                  ),
                ),
              ),
            ),
          ],
        ));
  }

  Widget _buildStepIndicator(int step, bool isActive,
      {bool completed = false}) {
    Color bgColor =
        isActive ? Theme.of(context).primaryColor : Colors.transparent;
    Color textColor = isActive ? Colors.white : Colors.grey.shade400;
    Border? border =
        isActive ? null : Border.all(color: Colors.grey.shade300, width: 2);
    Widget child = Text(step.toString(),
        style: TextStyle(color: textColor, fontWeight: FontWeight.bold));

    if (completed) {
      bgColor = Theme.of(context).primaryColor;
      textColor = Colors.white;
      border = null;
      child = const Icon(Icons.check, color: Colors.white, size: 16);
    }

    return Container(
      width: 32,
      height: 32,
      decoration: BoxDecoration(
        color: bgColor,
        border: border,
        shape: BoxShape.circle,
      ),
      alignment: Alignment.center,
      child: child,
    );
  }

  Widget _buildStepLine(bool completed) {
    return Container(
      width: 40,
      height: 2,
      color: completed ? Theme.of(context).primaryColor : Colors.grey.shade300,
      margin: const EdgeInsets.symmetric(horizontal: 4),
    );
  }

  Widget _buildPaceOption(String value, IconData icon, String label) {
    final isSelected = _selectedPace == value;
    final color = isSelected ? Theme.of(context).primaryColor : Colors.grey;
    final bgColor = isSelected
        ? Theme.of(context).primaryColor.withValues(alpha: 0.1)
        : Theme.of(context).cardColor;
    final borderColor =
        isSelected ? Theme.of(context).primaryColor : Colors.transparent;

    return InkWell(
      onTap: () {
        setState(() {
          _selectedPace = value;
        });
      },
      borderRadius: BorderRadius.circular(16),
      child: Container(
        padding: const EdgeInsets.symmetric(vertical: 16, horizontal: 8),
        decoration: BoxDecoration(
          color: bgColor,
          borderRadius: BorderRadius.circular(16),
          border: Border.all(color: borderColor),
          boxShadow: isSelected
              ? null
              : [
                  BoxShadow(
                      color: Colors.black.withValues(alpha: 0.05),
                      blurRadius: 4,
                      offset: const Offset(0, 2))
                ],
        ),
        child: Column(
          children: [
            Icon(icon, color: color),
            const SizedBox(height: 8),
            Text(label,
                style: TextStyle(
                    color: color, fontWeight: FontWeight.bold, fontSize: 12)),
          ],
        ),
      ),
    );
  }

  Widget _buildCategoryChip(IconData icon, String label, bool isSelected) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
      decoration: BoxDecoration(
        color: isSelected
            ? Theme.of(context).primaryColor
            : Theme.of(context).cardColor,
        borderRadius: BorderRadius.circular(12),
        border: isSelected
            ? null
            : Border.all(color: Colors.transparent), // Border logic
        boxShadow: isSelected
            ? [
                BoxShadow(
                    color:
                        Theme.of(context).primaryColor.withValues(alpha: 0.3),
                    blurRadius: 4,
                    offset: const Offset(0, 2))
              ]
            : [
                BoxShadow(
                    color: Colors.black.withValues(alpha: 0.05),
                    blurRadius: 2,
                    offset: const Offset(0, 1))
              ],
      ),
      child: Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          Icon(icon, size: 16, color: isSelected ? Colors.white : Colors.grey),
          const SizedBox(width: 8),
          Text(label,
              style: TextStyle(
                  color: isSelected ? Colors.white : Colors.grey,
                  fontWeight: FontWeight.bold,
                  fontSize: 12)),
        ],
      ),
    );
  }
}
